# Generated by Django 3.2.7 on 2021-09-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.TextField(max_length=50, verbose_name='skill Name')),
                ('percent', models.TextField(max_length=4, verbose_name='skill percent')),
            ],
        ),
    ]
