# Generated by Django 3.2.7 on 2021-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='percent',
            field=models.CharField(max_length=4, verbose_name='skill percent'),
        ),
    ]
