# Generated by Django 3.2.7 on 2021-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skills_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=50, verbose_name='skill Name'),
        ),
    ]
